spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation?serverTimezone=UTC&characterEncoding=UTF-8
    username: 'root'
    password: '0000'

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

logging.level:
  org.hibernate.SQL: debug
  org.springframework.transaction.interceptor: debug
  org.springframework.orm.jpa.JpaTransactionManager: debug
  org.hibernate.type.descriptor.BasicBinder: trace
  org.springframework.security: debug
#  org.apache.coyote.http11: trace

jwt:
  secret:
    key: amVvbmdod2EncyBwcm9qZWN0IHNlY3JldGtleS4uIOq3uCDriITqtazrj4Qg7J20IO2CpOulvCDtkoAg7IiYIOyXhuuLpC4uIOyepeuLtO2VnOuLpA==
#  org.apache.coyote.http11 : debug
#  http ?? ??? ??